[package]
name = "ratatop"
version = "0.1.0"
authors = ["Gabor Szabo <gabor@szabgab.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
sysinfo = "0.33.1"
